# Generated by Django 5.2.14 on 2026-06-05 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ecopuntos', models.IntegerField(default=50)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto')], default='nuevo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.zona')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'estado', '-created_at'], name='core_eviden_usuario_173cd6_idx')],
            },
        ),
    ]
