# Generated by Django 5.2.14 on 2026-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ecopuntos',
            field=models.IntegerField(default=0),
        ),
    ]
