# Generated by Django 5.2.14 on 2026-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_ecopuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
