# Generated by Django 5.2.14 on 2026-06-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evidencia_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20),
        ),
    ]
