# Generated by Django 5.2.14 on 2026-06-25 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recompensa_evidencia_fecha_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_reporte',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('admin', 'Administrador'), ('recolector', 'Recolector')], default='ciudadano', max_length=20),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin_estimada', models.TimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('parcialmente_completada', 'Parcialmente completada'), ('no_completada', 'No completada')], default='programada', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora_reporte', models.DateTimeField(blank=True, null=True)),
                ('distancia_restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('geometria_ruta', models.JSONField(blank=True, null=True)),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='core.zona')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.ruta')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ciudadano', 'ruta'), name='calificacion_unica_por_ruta')],
            },
        ),
    ]
