# Generated by Django 5.2.14 on 2026-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='lat_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='lng_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ultima_actualizacion_gps',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
