# Generated by Django 5.2.14 on 2026-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ruta_lat_actual_ruta_lng_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
